# Generated by Django 3.2.12 on 2023-05-10 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='userID',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
