# Generated by Django 3.2.18 on 2023-05-15 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_product_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='userID',
            new_name='customer',
        ),
    ]
