# Generated by Django 3.2.18 on 2023-05-15 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_userid_order_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
    ]
