# Generated by Django 4.2.1 on 2023-05-21 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20230515_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('cart', 'Giỏ hàng'), ('pending', 'Đang chờ xử lý'), ('shipped', 'Đã gửi hàng'), ('delivered', 'Đã giao hàng'), ('canceled', 'Đã hủy')], default='cart', max_length=50),
        ),
    ]
