# Generated by Django 4.2.1 on 2023-05-22 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_category_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='date',
        ),
    ]
