# Generated by Django 4.2.1 on 2023-05-22 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_category_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='canceled_reason',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
